### ISSUE TITLE
Rename repo to ssh4docker

### ISSUE THREAD

**Issue by demondave** [ByteDream/docker4ssh#2]
It can be really confusing if projects aren't named properly. So we should take a step in the right direction and rename the project from "docker4ssh" to "ssh4docker".

**Comment by ByteDream** [comment]
Rename: maybe, but not to ssh4docker. A repo named [ssh2docker](https://github.com/moul/ssh2docker) already exists, so the confusion may arise there too if you name it ssh4docker. Also, I personally like docker4ssh more. But as I said, renaming it to a unique name is an option (with v1.0.0 release).
